# 定数
PLAYER_ANY_SPEAKER = -101
PLAYER_NO_SPEAKER = -102
PLAYER_DEFAULT_SPEAKER = -103

# ソースタイプ
PLAYER_SOURCETYPE_FILE = 201
PLAYER_SOURCETYPE_URL = 202

# 設定読み出し定数
PLAYER_CONFIG_DEVICE = 301
PLAYER_CONFIG_ID = 302
PLAYER_CONFIG_SOURCE = 303
PLAYER_CONFIG_SOURCETYPE = 304

# ステータス
PLAYER_STATOUS_OK = 401
PLAYER_STATOUS_FAILD = 402

# 命令送信
PLAYER_SEND_INIT = 501
PLAYER_SEND_FILE = 502 #ファイルからストリーム生成
PLAYER_SEND_URL = 503 #URLからストリーム生成
PLAYER_SEND_PLAY = 504
PLAYER_SEND_PAUSE = 505
